CREATE TABLE IF NOT EXISTS `schema_comments` (
  `table_name` text NOT NULL,
  `column_name` text DEFAULT '' NOT NULL,
  `comment_type` text DEFAULT 'column' NOT NULL,
  `comment` text NOT NULL,
  `updated_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
  PRIMARY KEY (`table_name`, `column_name`)
);
--> statement-breakpoint
INSERT OR REPLACE INTO `schema_comments` (`table_name`, `column_name`, `comment_type`, `comment`, `updated_at`) VALUES
('users', '', 'table', '用户账号、角色和个人资料', CURRENT_TIMESTAMP),
('users', 'id', 'column', '用户唯一标识', CURRENT_TIMESTAMP),
('users', 'username', 'column', '登录用户名，系统内唯一', CURRENT_TIMESTAMP),
('users', 'password_hash', 'column', '登录密码哈希值', CURRENT_TIMESTAMP),
('users', 'role', 'column', '系统角色，用于权限控制', CURRENT_TIMESTAMP),
('users', 'display_name', 'column', '用户显示名称', CURRENT_TIMESTAMP),
('users', 'phone', 'column', '联系电话', CURRENT_TIMESTAMP),
('users', 'avatar_key', 'column', '头像资源标识', CURRENT_TIMESTAMP),
('users', 'job_title', 'column', '岗位或职能标识', CURRENT_TIMESTAMP),
('users', 'tech_stacks', 'column', '技术栈 JSON 数组', CURRENT_TIMESTAMP),
('users', 'timezone', 'column', '用户默认时区', CURRENT_TIMESTAMP),
('users', 'is_active', 'column', '账号是否启用', CURRENT_TIMESTAMP),
('users', 'created_at', 'column', '创建时间', CURRENT_TIMESTAMP),
('users', 'updated_at', 'column', '最后更新时间', CURRENT_TIMESTAMP),
('boards', '', 'table', '看板基础信息', CURRENT_TIMESTAMP),
('boards', 'id', 'column', '看板唯一标识', CURRENT_TIMESTAMP),
('boards', 'name', 'column', '看板名称', CURRENT_TIMESTAMP),
('boards', 'description', 'column', '看板描述', CURRENT_TIMESTAMP),
('boards', 'owner_user_id', 'column', '看板归属用户 ID', CURRENT_TIMESTAMP),
('boards', 'created_at', 'column', '创建时间', CURRENT_TIMESTAMP),
('boards', 'updated_at', 'column', '最后更新时间', CURRENT_TIMESTAMP),
('board_members', '', 'table', '看板成员关系', CURRENT_TIMESTAMP),
('board_members', 'board_id', 'column', '看板 ID', CURRENT_TIMESTAMP),
('board_members', 'user_id', 'column', '成员用户 ID', CURRENT_TIMESTAMP),
('board_members', 'role', 'column', '成员在看板内的角色', CURRENT_TIMESTAMP),
('board_members', 'created_at', 'column', '加入时间', CURRENT_TIMESTAMP),
('teams', '', 'table', '团队基础信息', CURRENT_TIMESTAMP),
('teams', 'id', 'column', '团队唯一标识', CURRENT_TIMESTAMP),
('teams', 'name', 'column', '团队名称', CURRENT_TIMESTAMP),
('teams', 'description', 'column', '团队描述', CURRENT_TIMESTAMP),
('teams', 'owner_user_id', 'column', '团队负责人用户 ID', CURRENT_TIMESTAMP),
('teams', 'color', 'column', '团队展示颜色', CURRENT_TIMESTAMP),
('teams', 'created_at', 'column', '创建时间', CURRENT_TIMESTAMP),
('teams', 'updated_at', 'column', '最后更新时间', CURRENT_TIMESTAMP),
('team_members', '', 'table', '团队成员关系', CURRENT_TIMESTAMP),
('team_members', 'team_id', 'column', '团队 ID', CURRENT_TIMESTAMP),
('team_members', 'user_id', 'column', '成员用户 ID', CURRENT_TIMESTAMP),
('team_members', 'created_at', 'column', '加入时间', CURRENT_TIMESTAMP),
('board_teams', '', 'table', '看板与团队授权关系', CURRENT_TIMESTAMP),
('board_teams', 'board_id', 'column', '看板 ID', CURRENT_TIMESTAMP),
('board_teams', 'team_id', 'column', '团队 ID', CURRENT_TIMESTAMP),
('board_teams', 'created_at', 'column', '授权时间', CURRENT_TIMESTAMP),
('projects', '', 'table', '项目基础信息和看板归属', CURRENT_TIMESTAMP),
('projects', 'id', 'column', '项目唯一标识', CURRENT_TIMESTAMP),
('projects', 'board_id', 'column', '所属看板 ID', CURRENT_TIMESTAMP),
('projects', 'team_id', 'column', '所属团队 ID', CURRENT_TIMESTAMP),
('projects', 'owner_user_id', 'column', '项目归属用户 ID', CURRENT_TIMESTAMP),
('projects', 'name', 'column', '项目名称', CURRENT_TIMESTAMP),
('projects', 'description', 'column', '项目描述', CURRENT_TIMESTAMP),
('projects', 'owner', 'column', '项目归属人显示名称，兼容历史数据', CURRENT_TIMESTAMP),
('projects', 'color', 'column', '项目展示颜色', CURRENT_TIMESTAMP),
('projects', 'health', 'column', '项目健康状态', CURRENT_TIMESTAMP),
('projects', 'status', 'column', '项目状态', CURRENT_TIMESTAMP),
('projects', 'summary', 'column', '项目摘要', CURRENT_TIMESTAMP),
('projects', 'archived_at', 'column', '归档时间', CURRENT_TIMESTAMP),
('projects', 'order_index', 'column', '项目排序序号', CURRENT_TIMESTAMP),
('projects', 'created_at', 'column', '创建时间', CURRENT_TIMESTAMP),
('projects', 'updated_at', 'column', '最后更新时间', CURRENT_TIMESTAMP),
('tasks', '', 'table', '任务卡片信息', CURRENT_TIMESTAMP),
('tasks', 'id', 'column', '任务唯一标识', CURRENT_TIMESTAMP),
('tasks', 'project_id', 'column', '所属项目 ID', CURRENT_TIMESTAMP),
('tasks', 'title', 'column', '任务标题', CURRENT_TIMESTAMP),
('tasks', 'description', 'column', '任务描述', CURRENT_TIMESTAMP),
('tasks', 'status', 'column', '任务所在阶段', CURRENT_TIMESTAMP),
('tasks', 'priority', 'column', '任务优先级', CURRENT_TIMESTAMP),
('tasks', 'owner_user_id', 'column', '负责人用户 ID', CURRENT_TIMESTAMP),
('tasks', 'owner', 'column', '负责人显示名称，兼容历史数据', CURRENT_TIMESTAMP),
('tasks', 'tester_user_id', 'column', '测试人员用户 ID', CURRENT_TIMESTAMP),
('tasks', 'tester', 'column', '测试人员显示名称，兼容历史数据', CURRENT_TIMESTAMP),
('tasks', 'workload_days', 'column', '任务工作量，单位为人天', CURRENT_TIMESTAMP),
('tasks', 'start_date', 'column', '计划开始日期', CURRENT_TIMESTAMP),
('tasks', 'design_due_date', 'column', '设计截止日期', CURRENT_TIMESTAMP),
('tasks', 'test_due_date', 'column', '测试截止日期', CURRENT_TIMESTAMP),
('tasks', 'due_date', 'column', '最终截止日期', CURRENT_TIMESTAMP),
('tasks', 'estimate', 'column', '任务估算值', CURRENT_TIMESTAMP),
('tasks', 'progress', 'column', '任务进度百分比', CURRENT_TIMESTAMP),
('tasks', 'blockers', 'column', '阻塞项数量', CURRENT_TIMESTAMP),
('tasks', 'blocked_reason', 'column', '阻塞原因说明', CURRENT_TIMESTAMP),
('tasks', 'tags', 'column', '任务标签 JSON 数组', CURRENT_TIMESTAMP),
('tasks', 'order_index', 'column', '任务在阶段内的排序序号', CURRENT_TIMESTAMP),
('tasks', 'deleted_at', 'column', '软删除时间', CURRENT_TIMESTAMP),
('tasks', 'completed_at', 'column', '完成时间', CURRENT_TIMESTAMP),
('tasks', 'created_at', 'column', '创建时间', CURRENT_TIMESTAMP),
('tasks', 'updated_at', 'column', '最后更新时间', CURRENT_TIMESTAMP),
('subtasks', '', 'table', '任务拆解子项', CURRENT_TIMESTAMP),
('subtasks', 'id', 'column', '子任务唯一标识', CURRENT_TIMESTAMP),
('subtasks', 'task_id', 'column', '所属任务 ID', CURRENT_TIMESTAMP),
('subtasks', 'title', 'column', '子任务标题', CURRENT_TIMESTAMP),
('subtasks', 'done', 'column', '是否完成', CURRENT_TIMESTAMP),
('subtasks', 'order_index', 'column', '子任务排序序号', CURRENT_TIMESTAMP),
('subtasks', 'created_at', 'column', '创建时间', CURRENT_TIMESTAMP),
('subtasks', 'updated_at', 'column', '最后更新时间', CURRENT_TIMESTAMP),
('task_activity', '', 'table', '任务和项目协作动态', CURRENT_TIMESTAMP),
('task_activity', 'id', 'column', '动态记录唯一标识', CURRENT_TIMESTAMP),
('task_activity', 'board_id', 'column', '所属看板 ID', CURRENT_TIMESTAMP),
('task_activity', 'entity_type', 'column', '动态关联实体类型', CURRENT_TIMESTAMP),
('task_activity', 'entity_id', 'column', '动态关联实体 ID', CURRENT_TIMESTAMP),
('task_activity', 'project_id', 'column', '关联项目 ID', CURRENT_TIMESTAMP),
('task_activity', 'task_id', 'column', '关联任务 ID', CURRENT_TIMESTAMP),
('task_activity', 'action', 'column', '动态动作类型', CURRENT_TIMESTAMP),
('task_activity', 'message', 'column', '动态展示文案', CURRENT_TIMESTAMP),
('task_activity', 'meta', 'column', '动态扩展信息 JSON', CURRENT_TIMESTAMP),
('task_activity', 'created_at', 'column', '创建时间', CURRENT_TIMESTAMP),
('audit_logs', '', 'table', '审计日志', CURRENT_TIMESTAMP),
('audit_logs', 'id', 'column', '审计日志唯一标识', CURRENT_TIMESTAMP),
('audit_logs', 'actor_user_id', 'column', '操作人用户 ID', CURRENT_TIMESTAMP),
('audit_logs', 'actor_username', 'column', '操作人用户名', CURRENT_TIMESTAMP),
('audit_logs', 'actor_role', 'column', '操作人角色', CURRENT_TIMESTAMP),
('audit_logs', 'action', 'column', '审计动作', CURRENT_TIMESTAMP),
('audit_logs', 'resource_type', 'column', '资源类型', CURRENT_TIMESTAMP),
('audit_logs', 'resource_id', 'column', '资源 ID', CURRENT_TIMESTAMP),
('audit_logs', 'board_id', 'column', '关联看板 ID', CURRENT_TIMESTAMP),
('audit_logs', 'result', 'column', '操作结果', CURRENT_TIMESTAMP),
('audit_logs', 'message', 'column', '审计消息', CURRENT_TIMESTAMP),
('audit_logs', 'ip_address', 'column', '来源 IP 地址', CURRENT_TIMESTAMP),
('audit_logs', 'user_agent', 'column', '客户端 User-Agent', CURRENT_TIMESTAMP),
('audit_logs', 'request_id', 'column', '请求追踪 ID', CURRENT_TIMESTAMP),
('audit_logs', 'metadata', 'column', '审计扩展信息 JSON', CURRENT_TIMESTAMP),
('audit_logs', 'created_at', 'column', '创建时间', CURRENT_TIMESTAMP),
('system_parameters', '', 'table', '系统参数配置', CURRENT_TIMESTAMP),
('system_parameters', 'key', 'column', '参数键名', CURRENT_TIMESTAMP),
('system_parameters', 'value', 'column', '参数值', CURRENT_TIMESTAMP),
('system_parameters', 'label', 'column', '参数显示名称', CURRENT_TIMESTAMP),
('system_parameters', 'value_type', 'column', '参数值类型', CURRENT_TIMESTAMP),
('system_parameters', 'parameter_group', 'column', '参数分组', CURRENT_TIMESTAMP),
('system_parameters', 'unit', 'column', '参数单位', CURRENT_TIMESTAMP),
('system_parameters', 'min_value', 'column', '数字参数最小值', CURRENT_TIMESTAMP),
('system_parameters', 'max_value', 'column', '数字参数最大值', CURRENT_TIMESTAMP),
('system_parameters', 'order_index', 'column', '参数排序序号', CURRENT_TIMESTAMP),
('system_parameters', 'updated_at', 'column', '最后更新时间', CURRENT_TIMESTAMP),
('schema_comments', '', 'table', '数据库表和字段说明字典', CURRENT_TIMESTAMP),
('schema_comments', 'table_name', 'column', '表名', CURRENT_TIMESTAMP),
('schema_comments', 'column_name', 'column', '字段名，空字符串表示表注释', CURRENT_TIMESTAMP),
('schema_comments', 'comment_type', 'column', '注释类型，table 或 column', CURRENT_TIMESTAMP),
('schema_comments', 'comment', 'column', '注释内容', CURRENT_TIMESTAMP),
('schema_comments', 'updated_at', 'column', '最后更新时间', CURRENT_TIMESTAMP);
